# Generated by Django 5.1.7 on 2025-03-12 10:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testentry',
            name='email',
        ),
        migrations.RemoveField(
            model_name='testentry',
            name='message',
        ),
        migrations.AddField(
            model_name='testentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testentry',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
